### ISSUE TITLE
Set up spec compliance checker

### ISSUE THREAD

**Issue by seanmonstar** [hyperium/h3#109]
The s2n-quic maintainers created a neat [tool to check compliance](https://github.com/aws/s2n-quic/tree/main/common/duvet) with specifications with comments in the code. We can set it up to run as a CI job against [RFC 9114](https://httpwg.org/specs/rfc9114.html), and have it publish to the `gh-pages` branch.

This [GH Action](https://github.com/aws/s2n-quic/tree/main/.github/actions/duvet) is very close to what we want. The only difference is to remove the S3 bucket stuff, and just push to `gh-pages`.

Once this is setup, we can start systematically adding comments or fixing things to improve our handling of the HTTP/3 spec.

**Comment by eagr** [comment]
I would like to help out if it's ok.

**Comment by seanmonstar** [comment]
Help is always welcome!

**Comment by eagr** [comment]
Duvet is used internally, prone to change in terms of api or file structure. Rather than *checking out* the code in the action, I think it might be better to just inline duvet in the `h3` repo, so that the checks won’t break due to changes in the aws repo.

I have something that’s close to what you described, in this [fork](https://github.com/eagr/h3). But I still need to do some digging to figure out how the spec parsing/extraction works.

Would love some pointers for
* What is your preferred way to give credit to code from a different project?
* What is the preferred path for the report? From the current setting in the fork, I think the report can be accessed via SITE/h3/ci/compliance/report.html.

**Comment by seanmonstar** [comment]
I wonder if that team would be interested in publishing the crate, so we could depend on versions. @camshaft?

**Comment by camshaft** [comment]
Let me talk to the team today

**Comment by camshaft** [comment]
Alright, we're getting together a plan to publish the tool for external consumption.

My recommendation for until then is just clone the s2n-quic codebase and compile it rather than copy the source. We won't move the location until you're fully migrated to the published version.
