### ISSUE TITLE
Error when running server example

### ISSUE THREAD

**Issue by SergeiMinaev** [hyperium/h3#51]
```
$ cargo run --example server selfsigned 
Finished dev [unoptimized + debuginfo] target(s) in 0.19s
Running target/debug/examples/server selfsigned
```

I'm trying to connect via curl:
```
$ curl --http3 https://localhost:4433
```
After that, an error occurs:
```
$ cargo run --example server selfsigned 
    Finished dev [unoptimized + debuginfo] target(s) in 0.21s
     Running `target/debug/examples/server selfsigned`
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: h3::Error { kind: Transport, cause: ApplicationClosed(ApplicationClose { error_code: 0, reason: b"" }) }', examples/server.rs:124:80
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

If I try to connnect via `cargo run --example client` there's another error:
```
$ cargo run --example client https://localhost:4433
    Finished dev [unoptimized + debuginfo] target(s) in 0.18s
     Running `target/debug/examples/client 'https://localhost:4433'`
DNS Lookup for https://localhost:4433/: 127.0.0.1:4433
Error: ConnectionClosed(ConnectionClose { error_code: Code::crypto(78), frame_type: None, reason: b"peer doesn't support any known protocol" })

```

**Comment by seanmonstar** [comment]
Ah, looks like the server example has an old set of ALPN protocols set. When I locally updated that to `h3-29`, it worked.

**Comment by SergeiMinaev** [comment]
I've changed `server_config.protocols(&[b"h3-27"]);` to `server_config.protocols(&[b"h3-29"]);`.
After that, the client example returns another error:
```
$ cargo run --example client https://localhost:4433
    Finished dev [unoptimized + debuginfo] target(s) in 0.26s
     Running `target/debug/examples/client 'https://localhost:4433'`
DNS Lookup for https://localhost:4433/: 127.0.0.1:4433
Error: TransportError(Error { code: Code::crypto(2a), frame: None, reason: "invalid certificate: UnknownIssuer" }
```

But when I connecting with curl, tokio is still panicking:
```
$ cargo run --example server selfsigned 
   Compiling examples v0.0.0 (/media/Program/rust/h3/examples)
    Finished dev [unoptimized + debuginfo] target(s) in 7.94s
     Running `target/debug/examples/server selfsigned
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: h3::Error { kind: Transport, cause: ApplicationClosed(ApplicationClose { error_code: 0, reason: b"" }) }', examples/server.rs:124:80
```

My curl is built with quiche-0.9.0-r1.

**Comment by stammw** [comment]
Thanks for reporting this!

#52 should make everything work. Note that for the moment, the server only returns 404 errors...

**Comment by SergeiMinaev** [comment]
Thanks! Now the client and the server examples works together. The client receives http responses without errors. But the server  **sometimes** raises this errors:
```
$ cargo run --example server selfsigned 
    Finished dev [unoptimized + debuginfo] target(s) in 0.56s
     Running `target/debug/examples/server selfsigned`
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: h3::Error { kind: Transport, cause: ApplicationClosed(ApplicationClose { error_code: 0, reason: b"" }) }', examples/server.rs:124:80
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: h3::Error { kind: Transport, cause: ApplicationClosed(ApplicationClose { error_code: 0, reason: b"" }) }', examples/server.rs:124:80
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: h3::Error { kind: Transport, cause: TimedOut }', examples/server.rs:124:80
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: h3::Error { code: H3_GENERAL_PROTOCOL_ERROR, cause: Write(ConnectionClosed(TimedOut)) }', examples/server.rs:142:51
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: h3::Error { kind: Transport, cause: TimedOut }', examples/server.rs:124:80
```

What does it mean? Is there anything I can do about it?

**Comment by stammw** [comment]
* `ApplicationClosed(ApplicationClose { error_code: 0, reason: b"" })` means the client has closed the connection cleanly. The message should perhaps be a bit more explanatory, so the user doesn't have to know the HTTP3 spec. 
* `TimedOut` is because the lib doesn't handle expected timeouts from the local side correctly. I guess.
* I'm not sure about `code: H3_GENERAL_PROTOCOL_ERROR, cause: Write(ConnectionClosed(TimedOut))` but it could be the same source as the former, but happening as the stack is writing for some reason.

If you can reproduce this with `RUST_BACKTRACE=1`, that could help. 

I've been preparing a [big PR](https://github.com/hyperium/h3/tree/features/stammw%2Fabrupt-closure) to enhance abrupt closures and error management behavior a good deal. Unfortunately I did not have much time and energy to finish it. I should have more of those in the upcoming month. I hope I'll be able to deliver it soon !

Did you test again with curl ?

**Comment by SergeiMinaev** [comment]
@stammw , thank you for the info! This helped a little :)

Reproduce with RUST_BACKTRACE=1 ("allow-insecure-client-example" branch):
client example (same with curl) - https://pastebin.com/T6J6D52w . This always happens when I connecting via curl and sometimes when connecting via client example. Other errors are rare, I couldn't reproduce them.

**Comment by SergeiMinaev** [comment]
I'm new to Rust and I'm struggling a bit with its syntax, but the error ( https://pastebin.com/T6J6D52w ) disappears when I change 
```
while let Some((req, mut stream)) = h3_conn.accept().await.unwrap() {
...
}
```
to
```
match h3_conn.accept().await {
  Ok(r) => {
    let (req, mut stream) = r.unwrap();
  },
}
```

**Comment by stammw** [comment]
Thanks for reporting this. 

The server's `accept()` should actually return `Ok(None)` instead of `Err(ApplicationClosed(ApplicationClose { error_code: 0, reason: b"" })`. That's the idiomatic way of expressing the end of a stream (of incoming requests in this case).

Thanks for reporting. Now trying again on my current WIP, the normal connection closure handling is even worse... 

Unfortunately this issue is in the scope of my current work, so a PR for that matter wouldn't make much sense. But if you'd like to help, we'd like to turn the server example into a basic file server. 

Welcome to you, new rustacean !

**Comment by SergeiMinaev** [comment]
> The server's `accept()` should actually return `Ok(None)` instead of `Err(ApplicationClosed(ApplicationClose { error_code: 0, reason: b"" })`. That's the idiomatic way of expressing the end of a stream (of incoming requests in this case).

Oh, I got it. Ty! I'll try to do something again.

**Comment by stammw** [comment]
Maybe you could try to use #54 to see if the behavior matches your expectations.
