### ISSUE TITLE
h3 and hyper integration

### ISSUE THREAD

**Issue by FrankSpitulski** [hyperium/h3#76]
hi all, is there a roadmap for hyper integration? I'd be happy to help with what I can if there are some tasks left. I don't see any active PRs or related issues at the moment though.

**Comment by stammw** [comment]
HI Frank,

There is no roadmap on this, though @seanmonstar might have something in mind IIRC.

To me it's rather simple: we'll start when h3 is on crates.io :upside_down_face:. So when the docs are written and merged that should be OK for a v0.1.

Did you have a look in hyper's issues ? There might be some info there as well.

Integration in Hyper will be far from a trivial work though, since new type parameters have to be handled IIRC.

Once it is a bit clearer in my mind I should be able to find some tasks for you. But don't hesitate to dig in the stack to find something by yourself :) I'm quite busy right now on a new day job.

It's really encouraging to see you offer your help, thanks a lot! :D
